<?php

use Illuminate\Database\Seeder;

class StepMastersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('step_masters')->insert([
            [
                'id' => 1,
                'menu_master_id' => 1,
                'step_number' => 1,
                'name' => "ウォール・プッシュアップ",
                'description' => '',
                'set1_start_count' => 10,
                'set2_start_count' => 15,
                'set3_start_count' => 25,
                'set3_master_count' => 50,
                'level1_rep_count' =>10,
                'level1_set_count' =>1,
                'level2_rep_count' =>25,
                'level2_set_count' =>2,
                'level3_rep_count' =>50,
                'level3_set_count' =>3,
            ],
            [
                'id' => 2,
                'menu_master_id' => 1,
                'step_number' => 2,
                'name' => "インクライン・プッシュアップ",
                'description' => '',
                'set1_start_count' => 10,
                'set2_start_count' => 15,
                'set3_start_count' => 20,
                'set3_master_count' => 40,
                'level1_rep_count' =>10,
                'level1_set_count' =>1,
                'level2_rep_count' =>20,
                'level2_set_count' =>2,
                'level3_rep_count' =>40,
                'level3_set_count' =>3,
            ],
            [
                'id' => 3,
                'menu_master_id' => 1,
                'step_number' => 3,
                'name' => "ニーリング・プッシュアップ",
                'description' => '',
                'set1_start_count' => 10,
                'set2_start_count' => 12,
                'set3_start_count' => 15,
                'set3_master_count' => 30,
                'level1_rep_count' =>10,
                'level1_set_count' =>1,
                'level2_rep_count' =>15,
                'level2_set_count' =>2,
                'level3_rep_count' =>30,
                'level3_set_count' =>3,
            ],
            [
                'id' => 4,
                'menu_master_id' => 1,
                'step_number' => 4,
                'name' => "ハーフ・プッシュアップ",
                'description' => '',
                'set1_start_count' => 8,
                'set2_start_count' => 10,
                'set3_start_count' => 25,
                'set3_master_count' => 0,
                'level1_rep_count' => 8,
                'level1_set_count' => 1,
                'level2_rep_count' => 12,
                'level2_set_count' => 2,
                'level3_rep_count' => 25,
                'level3_set_count' => 2,
            ],
            [
                'id' => 5,
                'menu_master_id' => 1,
                'step_number' => 5,
                'name' => "フル・プッシュアップ",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 8,
                'set3_start_count' => 20,
                'set3_master_count' => 0,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 10,
                'level2_set_count' => 2,
                'level3_rep_count' => 20,
                'level3_set_count' => 2,
            ],
            [
                'id' => 6,
                'menu_master_id' => 1,
                'step_number' => 6,
                'name' => "クローズ・プッシュアップ",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 8,
                'set3_start_count' => 20,
                'set3_master_count' => 0,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 10,
                'level2_set_count' => 2,
                'level3_rep_count' => 20,
                'level3_set_count' => 2,
            ],
            [
                'id' => 7,
                'menu_master_id' => 1,
                'step_number' => 7,
                'name' => "アンイーブン・プッシュアップ",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 8,
                'set3_start_count' => 20,
                'set3_master_count' => 0,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 10,
                'level2_set_count' => 2,
                'level3_rep_count' => 20,
                'level3_set_count' => 2,
            ],
            [
                'id' => 8,
                'menu_master_id' => 1,
                'step_number' => 8,
                'name' => "ハーフ・ワンアーム・プッシュアップ",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 8,
                'set3_start_count' => 10,
                'set3_master_count' => 20,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 10,
                'level2_set_count' => 2,
                'level3_rep_count' => 20,
                'level3_set_count' => 3,
            ],
            [
                'id' => 9,
                'menu_master_id' => 1,
                'step_number' => 9,
                'name' => "レバー・プッシュアップ",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 8,
                'set3_start_count' => 20,
                'set3_master_count' => 0,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 10,
                'level2_set_count' => 2,
                'level3_rep_count' => 20,
                'level3_set_count' => 2,
            ],
            [
                'id' => 10,
                'menu_master_id' => 1,
                'step_number' => 10,
                'name' => "ワンアーム・プッシュアップ",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 8,
                'set3_start_count' => 50,
                'set3_master_count' => 0,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 10,
                'level2_set_count' => 2,
                'level3_rep_count' => 100,
                'level3_set_count' => 1,
            ],
            [
                'id' => 11,
                'menu_master_id' => 2,
                'step_number' => 1,
                'name' => "ショルダースタンド・スクワット",
                'description' => '',
                'set1_start_count' => 10,
                'set2_start_count' => 15,
                'set3_start_count' => 25,
                'set3_master_count' => 50,
                'level1_rep_count' => 10,
                'level1_set_count' => 1,
                'level2_rep_count' => 25,
                'level2_set_count' => 2,
                'level3_rep_count' => 50,
                'level3_set_count' => 3,
            ],
            [
                'id' => 12,
                'menu_master_id' => 2,
                'step_number' => 2,
                'name' => "ジャックナイフ・スクワット",
                'description' => '',
                'set1_start_count' => 10,
                'set2_start_count' => 15,
                'set3_start_count' => 20,
                'set3_master_count' => 40,
                'level1_rep_count' => 10,
                'level1_set_count' => 1,
                'level2_rep_count' => 20,
                'level2_set_count' => 2,
                'level3_rep_count' => 40,
                'level3_set_count' => 3,
            ],
            [
                'id' => 13,
                'menu_master_id' => 2,
                'step_number' => 3,
                'name' => "サポーティッド・スクワット",
                'description' => '',
                'set1_start_count' => 10,
                'set2_start_count' => 12,
                'set3_start_count' => 15,
                'set3_master_count' => 30,
                'level1_rep_count' => 10,
                'level1_set_count' => 1,
                'level2_rep_count' => 15,
                'level2_set_count' => 2,
                'level3_rep_count' => 30,
                'level3_set_count' => 3,
            ],
            [
                'id' => 14,
                'menu_master_id' => 2,
                'step_number' => 4,
                'name' => "ハーフ・スクワット",
                'description' => '',
                'set1_start_count' => 8,
                'set2_start_count' => 15,
                'set3_start_count' => 50,
                'set3_master_count' => 0,
                'level1_rep_count' => 8,
                'level1_set_count' => 1,
                'level2_rep_count' => 35,
                'level2_set_count' => 2,
                'level3_rep_count' => 50,
                'level3_set_count' => 2,
            ],
            [
                'id' => 15,
                'menu_master_id' => 2,
                'step_number' => 5,
                'name' => "フル・スクワット",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 8,
                'set3_start_count' => 30,
                'set3_master_count' => 0,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 10,
                'level2_set_count' => 2,
                'level3_rep_count' => 30,
                'level3_set_count' => 2,
            ],
            [
                'id' => 16,
                'menu_master_id' => 2,
                'step_number' => 6,
                'name' => "クローズ・スクワット",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 8,
                'set3_start_count' => 20,
                'set3_master_count' => 0,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 10,
                'level2_set_count' => 2,
                'level3_rep_count' => 20,
                'level3_set_count' => 2,
            ],
            [
                'id' => 17,
                'menu_master_id' => 2,
                'step_number' => 7,
                'name' => "アンイーブン・スクワット",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 8,
                'set3_start_count' => 20,
                'set3_master_count' => 0,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 10,
                'level2_set_count' => 2,
                'level3_rep_count' => 20,
                'level3_set_count' => 2,
            ],
            [
                'id' => 18,
                'menu_master_id' => 2,
                'step_number' => 8,
                'name' => "ハーフ・ワンレッグ・スクワット",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 8,
                'set3_start_count' => 20,
                'set3_master_count' => 0,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 10,
                'level2_set_count' => 2,
                'level3_rep_count' => 20,
                'level3_set_count' => 2,
            ],
            [
                'id' => 19,
                'menu_master_id' => 2,
                'step_number' => 9,
                'name' => "アシステッド・ワンレッグ・スクワット",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 8,
                'set3_start_count' => 20,
                'set3_master_count' => 0,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 10,
                'level2_set_count' => 2,
                'level3_rep_count' => 20,
                'level3_set_count' => 2,
            ],
            [
                'id' => 20,
                'menu_master_id' => 2,
                'step_number' => 10,
                'name' => "ワンレッグ・スクワット",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 8,
                'set3_start_count' => 50,
                'set3_master_count' => 0,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 10,
                'level2_set_count' => 2,
                'level3_rep_count' => 50,
                'level3_set_count' => 2,
            ],
            [
                'id' => 21,
                'menu_master_id' => 3,
                'step_number' => 1,
                'name' => "ヴァーチカル・プル",
                'description' => '',
                'set1_start_count' => 10,
                'set2_start_count' => 15,
                'set3_start_count' => 20,
                'set3_master_count' => 40,
                'level1_rep_count' => 10,
                'level1_set_count' => 1,
                'level2_rep_count' => 20,
                'level2_set_count' => 2,
                'level3_rep_count' => 40,
                'level3_set_count' => 3,
            ],
            [
                'id' => 22,
                'menu_master_id' => 3,
                'step_number' => 2,
                'name' => "ホリゾンタル・プル",
                'description' => '',
                'set1_start_count' => 10,
                'set2_start_count' => 15,
                'set3_start_count' => 25,
                'set3_master_count' => 30,
                'level1_rep_count' => 10,
                'level1_set_count' => 1,
                'level2_rep_count' => 25,
                'level2_set_count' => 2,
                'level3_rep_count' => 30,
                'level3_set_count' => 3,
            ],
            [
                'id' => 23,
                'menu_master_id' => 3,
                'step_number' => 3,
                'name' => "ジャックナイフ・プル",
                'description' => '',
                'set1_start_count' => 10,
                'set2_start_count' => 12,
                'set3_start_count' => 15,
                'set3_master_count' => 20,
                'level1_rep_count' => 10,
                'level1_set_count' => 1,
                'level2_rep_count' => 15,
                'level2_set_count' => 2,
                'level3_rep_count' => 20,
                'level3_set_count' => 3,
            ],
            [
                'id' => 24,
                'menu_master_id' => 3,
                'step_number' => 4,
                'name' => "ハーフ・プルアップ",
                'description' => '',
                'set1_start_count' => 8,
                'set2_start_count' => 9,
                'set3_start_count' => 11,
                'set3_master_count' => 15,
                'level1_rep_count' => 8,
                'level1_set_count' => 1,
                'level2_rep_count' => 11,
                'level2_set_count' => 2,
                'level3_rep_count' => 15,
                'level3_set_count' => 3,
            ],
            [
                'id' => 25,
                'menu_master_id' => 3,
                'step_number' => 5,
                'name' => "フル・プルアップ",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 7,
                'set3_start_count' => 8,
                'set3_master_count' => 10,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 8,
                'level2_set_count' => 2,
                'level3_rep_count' => 10,
                'level3_set_count' => 3,
            ],
            [
                'id' => 26,
                'menu_master_id' => 3,
                'step_number' => 6,
                'name' => "クローズ・プルアップ",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 9,
                'set3_start_count' => 11,
                'set3_master_count' => 15,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 8,
                'level2_set_count' => 2,
                'level3_rep_count' => 10,
                'level3_set_count' => 2,
            ],
            [
                'id' => 27,
                'menu_master_id' => 3,
                'step_number' => 7,
                'name' => "アンイーブン・プルアップ",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 6,
                'set3_start_count' => 9,
                'set3_master_count' => 0,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 7,
                'level2_set_count' => 2,
                'level3_rep_count' => 9,
                'level3_set_count' => 2,
            ],

            [
                'id' => 28,
                'menu_master_id' => 3,
                'step_number' => 8,
                'name' => "ハーフ・ワンアーム・プルアップ",
                'description' => '',
                'set1_start_count' => 4,
                'set2_start_count' => 5,
                'set3_start_count' => 8,
                'set3_master_count' => 0,
                'level1_rep_count' => 4,
                'level1_set_count' => 1,
                'level2_rep_count' => 6,
                'level2_set_count' => 2,
                'level3_rep_count' => 8,
                'level3_set_count' => 2,
            ],
            [
                'id' => 29,
                'menu_master_id' => 3,
                'step_number' => 9,
                'name' => "アシステッド・ワンアーム・プルアップ",
                'description' => '',
                'set1_start_count' => 3,
                'set2_start_count' => 4,
                'set3_start_count' => 7,
                'set3_master_count' => 0,
                'level1_rep_count' => 3,
                'level1_set_count' => 1,
                'level2_rep_count' => 5,
                'level2_set_count' => 2,
                'level3_rep_count' => 7,
                'level3_set_count' => 2,
            ],
            [
                'id' => 30,
                'menu_master_id' => 3,
                'step_number' => 10,
                'name' => "ワンアーム・プルアップ",
                'description' => '',
                'set1_start_count' => 1,
                'set2_start_count' => 2,
                'set3_start_count' => 6,
                'set3_master_count' => 0,
                'level1_rep_count' => 1,
                'level1_set_count' => 1,
                'level2_rep_count' => 3,
                'level2_set_count' => 2,
                'level3_rep_count' => 6,
                'level3_set_count' => 2,
            ],
            [
                'id' => 31,
                'menu_master_id' => 4,
                'step_number' => 1,
                'name' => "ニー・タック",
                'description' => '',
                'set1_start_count' => 10,
                'set2_start_count' => 15,
                'set3_start_count' => 25,
                'set3_master_count' => 40,
                'level1_rep_count' => 10,
                'level1_set_count' => 1,
                'level2_rep_count' => 25,
                'level2_set_count' => 2,
                'level3_rep_count' => 40,
                'level3_set_count' => 3,
            ],
            [
                'id' => 32,
                'menu_master_id' => 4,
                'step_number' => 2,
                'name' => "フラット・ニー・レイズ",
                'description' => '',
                'set1_start_count' => 10,
                'set2_start_count' => 15,
                'set3_start_count' => 20,
                'set3_master_count' => 35,
                'level1_rep_count' => 10,
                'level1_set_count' => 1,
                'level2_rep_count' => 20,
                'level2_set_count' => 2,
                'level3_rep_count' => 35,
                'level3_set_count' => 2,
            ],
            [
                'id' => 33,
                'menu_master_id' => 4,
                'step_number' => 3,
                'name' => "フラット・ベント・レッグレイズ",
                'description' => '',
                'set1_start_count' => 10,
                'set2_start_count' => 12,
                'set3_start_count' => 15,
                'set3_master_count' => 30,
                'level1_rep_count' => 10,
                'level1_set_count' => 1,
                'level2_rep_count' => 15,
                'level2_set_count' => 2,
                'level3_rep_count' => 30,
                'level3_set_count' => 2,
            ],
            [
                'id' => 34,
                'menu_master_id' => 4,
                'step_number' => 4,
                'name' => "フラット・フロッグ・レイズ",
                'description' => '',
                'set1_start_count' => 8,
                'set2_start_count' => 10,
                'set3_start_count' => 25,
                'set3_master_count' => 0,
                'level1_rep_count' => 8,
                'level1_set_count' => 1,
                'level2_rep_count' => 15,
                'level2_set_count' => 2,
                'level3_rep_count' => 25,
                'level3_set_count' => 2,
            ],
            [
                'id' => 35,
                'menu_master_id' => 4,
                'step_number' => 5,
                'name' => "フラット・ストレート・レッグレイズ",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 8,
                'set3_start_count' => 20,
                'set3_master_count' => 0,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 10,
                'level2_set_count' => 2,
                'level3_rep_count' => 20,
                'level3_set_count' => 2,
            ],
            [
                'id' => 36,
                'menu_master_id' => 4,
                'step_number' => 6,
                'name' => "ハンギング・ニー・レイズ",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 8,
                'set3_start_count' => 15,
                'set3_master_count' => 0,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 10,
                'level2_set_count' => 2,
                'level3_rep_count' => 15,
                'level3_set_count' => 2,
            ],
            [
                'id' => 37,
                'menu_master_id' => 4,
                'step_number' => 7,
                'name' => "ハンギング・ベント・レッグレイズ",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 8,
                'set3_start_count' => 15,
                'set3_master_count' => 0,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 10,
                'level2_set_count' => 2,
                'level3_rep_count' => 15,
                'level3_set_count' => 2,
            ],
            [
                'id' => 38,
                'menu_master_id' => 4,
                'step_number' => 8,
                'name' => "ハンギング・フロッグ・レイズ",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 8,
                'set3_start_count' => 15,
                'set3_master_count' => 0,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 10,
                'level2_set_count' => 2,
                'level3_rep_count' => 15,
                'level3_set_count' => 2,
            ],
            [
                'id' => 39,
                'menu_master_id' => 4,
                'step_number' => 9,
                'name' => "パーシャル・ストレート・レッグレイズ",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 8,
                'set3_start_count' => 15,
                'set3_master_count' => 0,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 10,
                'level2_set_count' => 2,
                'level3_rep_count' => 15,
                'level3_set_count' => 2,
            ],
            [
                'id' => 40,
                'menu_master_id' => 4,
                'step_number' => 10,
                'name' => "ハンギング・ストレート・レッグレイズ",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 8,
                'set3_start_count' => 30,
                'set3_master_count' => 0,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 10,
                'level2_set_count' => 2,
                'level3_rep_count' => 30,
                'level3_set_count' => 2,
            ],
            [
                'id' => 41,
                'menu_master_id' => 5,
                'step_number' => 1,
                'name' => "ショート・ブリッジ",
                'description' => '',
                'set1_start_count' => 10,
                'set2_start_count' => 15,
                'set3_start_count' => 25,
                'set3_master_count' => 50,
                'level1_rep_count' => 10,
                'level1_set_count' => 1,
                'level2_rep_count' => 25,
                'level2_set_count' => 2,
                'level3_rep_count' => 50,
                'level3_set_count' => 3,
            ],
            [
                'id' => 42,
                'menu_master_id' => 5,
                'step_number' => 2,
                'name' => "ストレート・ブリッジ",
                'description' => '',
                'set1_start_count' => 10,
                'set2_start_count' => 15,
                'set3_start_count' => 20,
                'set3_master_count' => 40,
                'level1_rep_count' => 10,
                'level1_set_count' => 1,
                'level2_rep_count' => 20,
                'level2_set_count' => 2,
                'level3_rep_count' => 40,
                'level3_set_count' => 3,
            ],
            [
                'id' => 43,
                'menu_master_id' => 5,
                'step_number' => 3,
                'name' => "アングルド・ブリッジ",
                'description' => '',
                'set1_start_count' => 8,
                'set2_start_count' => 10,
                'set3_start_count' => 15,
                'set3_master_count' => 30,
                'level1_rep_count' => 8,
                'level1_set_count' => 1,
                'level2_rep_count' => 15,
                'level2_set_count' => 2,
                'level3_rep_count' => 30,
                'level3_set_count' => 3,
            ],
            [
                'id' => 44,
                'menu_master_id' => 5,
                'step_number' => 4,
                'name' => "ヘッド・ブリッジ",
                'description' => '',
                'set1_start_count' => 8,
                'set2_start_count' => 10,
                'set3_start_count' => 25,
                'set3_master_count' => 0,
                'level1_rep_count' => 8,
                'level1_set_count' => 1,
                'level2_rep_count' => 15,
                'level2_set_count' => 2,
                'level3_rep_count' => 25,
                'level3_set_count' => 2,
            ],
            [
                'id' => 45,
                'menu_master_id' => 5,
                'step_number' => 5,
                'name' => "ハーフ・ブリッジ",
                'description' => '',
                'set1_start_count' => 8,
                'set2_start_count' => 10,
                'set3_start_count' => 20,
                'set3_master_count' => 0,
                'level1_rep_count' => 8,
                'level1_set_count' => 1,
                'level2_rep_count' => 15,
                'level2_set_count' => 2,
                'level3_rep_count' => 20,
                'level3_set_count' => 2,
            ],
            [
                'id' => 46,
                'menu_master_id' => 5,
                'step_number' => 6,
                'name' => "フル・ブリッジ",
                'description' => '',
                'set1_start_count' => 6,
                'set2_start_count' => 8,
                'set3_start_count' => 15,
                'set3_master_count' => 0,
                'level1_rep_count' => 6,
                'level1_set_count' => 1,
                'level2_rep_count' => 10,
                'level2_set_count' => 2,
                'level3_rep_count' => 15,
                'level3_set_count' => 2,
            ],
            [
                'id' => 47,
                'menu_master_id' => 5,
                'step_number' => 7,
                'name' => "ウォールウォーキング・ブリッジ(下向き)",
                'description' => '',
                'set1_start_count' => 3,
                'set2_start_count' => 4,
                'set3_start_count' => 10,
                'set3_master_count' => 0,
                'level1_rep_count' => 3,
                'level1_set_count' => 1,
                'level2_rep_count' => 6,
                'level2_set_count' => 2,
                'level3_rep_count' => 10,
                'level3_set_count' => 2,
            ],
            [
                'id' => 48,
                'menu_master_id' => 5,
                'step_number' => 8,
                'name' => "ウォールウォーキング・ブリッジ(上向き)",
                'description' => '',
                'set1_start_count' => 2,
                'set2_start_count' => 3,
                'set3_start_count' => 8,
                'set3_master_count' => 0,
                'level1_rep_count' => 2,
                'level1_set_count' => 1,
                'level2_rep_count' => 4,
                'level2_set_count' => 2,
                'level3_rep_count' => 8,
                'level3_set_count' => 2,
            ],
            [
                'id' => 49,
                'menu_master_id' => 5,
                'step_number' => 9,
                'name' => "クロージング・ブリッジ",
                'description' => '',
                'set1_start_count' => 1,
                'set2_start_count' => 2,
                'set3_start_count' => 6,
                'set3_master_count' => 0,
                'level1_rep_count' => 1,
                'level1_set_count' => 1,
                'level2_rep_count' => 3,
                'level2_set_count' => 2,
                'level3_rep_count' => 6,
                'level3_set_count' => 2,
            ],
            [
                'id' => 50,
                'menu_master_id' => 5,
                'step_number' => 10,
                'name' => "スタンド・トゥ・スタンド・ブリッジ",
                'description' => '',
                'set1_start_count' => 1,
                'set2_start_count' => 2,
                'set3_start_count' => 30,
                'set3_master_count' => 0,
                'level1_rep_count' => 1,
                'level1_set_count' => 1,
                'level2_rep_count' => 3,
                'level2_set_count' => 2,
                'level3_rep_count' => 30,
                'level3_set_count' => 2,
            ],
            [
                'id' => 51,
                'menu_master_id' => 6,
                'step_number' => 1,
                'name' => "ウォール・ヘッドスタンド",
                'description' => '',
                'set1_start_count' => 10030,
                'set2_start_count' => 10120,
                'set3_start_count' => 0,
                'set3_master_count' => 0,
                'level1_rep_count' => 30,
                'level1_set_count' => 1,
                'level2_rep_count' => 60,
                'level2_set_count' => 1,
                'level3_rep_count' => 120,
                'level3_set_count' => 1,
            ],
            [
                'id' => 52,
                'menu_master_id' => 6,
                'step_number' => 2,
                'name' => "クロウ・スタンド",
                'description' => '',
                'set1_start_count' => 10010,
                'set2_start_count' => 10060,
                'set3_start_count' => 0,
                'set3_master_count' => 0,
                'level1_rep_count' => 10,
                'level1_set_count' => 1,
                'level2_rep_count' => 30,
                'level2_set_count' => 1,
                'level3_rep_count' => 60,
                'level3_set_count' => 1,
            ],
            [
                'id' => 53,
                'menu_master_id' => 6,
                'step_number' => 3,
                'name' => "ウォール・ハンドスタンド",
                'description' => '',
                'set1_start_count' => 10030,
                'set2_start_count' => 10120,
                'set3_start_count' => 0,
                'set3_master_count' => 0,
                'level1_rep_count' => 30,
                'level1_set_count' => 1,
                'level2_rep_count' => 60,
                'level2_set_count' => 1,
                'level3_rep_count' => 120,
                'level3_set_count' => 1,
            ],
            [
                'id' => 54,
                'menu_master_id' => 6,
                'step_number' => 4,
                'name' => "ハーフ・スタンド・プッシュアップ",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 8,
                'set3_start_count' => 20,
                'set3_master_count' => 0,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 10,
                'level2_set_count' => 2,
                'level3_rep_count' => 20,
                'level3_set_count' => 2,
            ],
            [
                'id' => 55,
                'menu_master_id' => 6,
                'step_number' => 5,
                'name' => "ハンドスタンド・プッシュアップ",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 8,
                'set3_start_count' => 15,
                'set3_master_count' => 0,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 10,
                'level2_set_count' => 2,
                'level3_rep_count' => 15,
                'level3_set_count' => 2,
            ],
            [
                'id' => 56,
                'menu_master_id' => 6,
                'step_number' => 6,
                'name' => "クローズ・ハンドスタンド・プッシュアップ",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 7,
                'set3_start_count' => 12,
                'set3_master_count' => 0,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 9,
                'level2_set_count' => 2,
                'level3_rep_count' => 12,
                'level3_set_count' => 2,
            ],
            [
                'id' => 57,
                'menu_master_id' => 6,
                'step_number' => 7,
                'name' => "アンイーブン・ハンドスタンド・プッシュアップ",
                'description' => '',
                'set1_start_count' => 5,
                'set2_start_count' => 8,
                'set3_start_count' => 10,
                'set3_master_count' => 0,
                'level1_rep_count' => 5,
                'level1_set_count' => 1,
                'level2_rep_count' => 8,
                'level2_set_count' => 2,
                'level3_rep_count' => 10,
                'level3_set_count' => 2,
            ],
            [
                'id' => 58,
                'menu_master_id' => 6,
                'step_number' => 8,
                'name' => "ハーフ・ワンアーム・ハンドスタンド・プッシュアップ",
                'description' => '',
                'set1_start_count' => 4,
                'set2_start_count' => 5,
                'set3_start_count' => 8,
                'set3_master_count' => 0,
                'level1_rep_count' => 4,
                'level1_set_count' => 1,
                'level2_rep_count' => 6,
                'level2_set_count' => 2,
                'level3_rep_count' => 8,
                'level3_set_count' => 2,
            ],
            [
                'id' => 59,
                'menu_master_id' => 6,
                'step_number' => 9,
                'name' => "レバー・ハンドスタンド・プッシュアップ",
                'description' => '',
                'set1_start_count' => 2,
                'set2_start_count' => 4,
                'set3_start_count' => 6,
                'set3_master_count' => 0,
                'level1_rep_count' => 3,
                'level1_set_count' => 1,
                'level2_rep_count' => 4,
                'level2_set_count' => 2,
                'level3_rep_count' => 6,
                'level3_set_count' => 2,
            ],
            [
                'id' => 60,
                'menu_master_id' => 6,
                'step_number' => 10,
                'name' => "ワンアーム・ハンドスタンド・プッシュアップ",
                'description' => '',
                'set1_start_count' => 1,
                'set2_start_count' => 2,
                'set3_start_count' => 5,
                'set3_master_count' => 0,
                'level1_rep_count' => 1,
                'level1_set_count' => 1,
                'level2_rep_count' => 2,
                'level2_set_count' => 2,
                'level3_rep_count' => 5,
                'level3_set_count' => 1,
            ],
        ]);
    }
}
