staging:
  hostname: <hostname> # デプロイ先のホスト名
  stage: staging
  roles:
    - app
  deploy_path: /var/www/html
  branch: master
  become: <username> # デプロイを行うユーザ
production:
  hostname: <hostname> # デプロイ先のホスト名
  stage: production
  roles:
    - app
  deploy_path: /var/www/html
  branch: master
  become: <username> # デプロイを行うユーザ