<h1>ワークアウト一覧</h1>
<table>
    <tr>
        <th>
           日付
        </th>
        <th>
            メニュー
        </th>

        <th>
            ステップ
        </th>
        <th>
            回数
        </th>
    </tr>
</table>
<?php
    print_r(config('pritra.index1'));
    print_r(config('pritra.index2.subindex1'));
print_r(config('pritra.index2.subindex1.subvalue1'));